---
- name: "5.2.20 | PATCH | Ensure SSH Idle Timeout Interval is configured"
  block:
    - name: "5.2.20 | PATCH | Ensure SSH Idle Timeout Interval is configured | Add line in sshd_config for ClientAliveInterval"
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^ClientAliveInterval'
        line: "ClientAliveInterval {{ rhel8cis_sshd['clientaliveinterval'] }}"
      notify:
        - restart sshd

    - name: "5.2.20 | PATCH | Ensure SSH Idle Timeout Interval is configured | Ensure SSH ClientAliveCountMax set to <= 3"
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: '^ClientAliveCountMax'
        line: "ClientAliveCountMax {{ rhel8cis_sshd['clientalivecountmax'] }}"
      notify:
        - restart sshd
