---
- name: "5.4.1 | PATCH | Ensure custom authselect profile is used"
  block:
      - name: "5.4.1 | AUDIT | Ensure custom authselect profile is used | Gather profiles"
        shell: 'authselect current | grep "Profile ID: custom/"'
        failed_when: false
        changed_when: false
        check_mode: no
        register: rhel8cis_5_4_1_profiles

      - name: "5.4.1 | AUDIT | Ensure custom authselect profile is used | Show profiles"
        debug:
            msg:
                - "Below are the current custom profiles"
                - "{{ rhel8cis_5_4_1_profiles.stdout_lines }}"

      - name: "5.4.1 | PATCH | Ensure custom authselect profile is used | Create custom profiles"
        shell: authselect create-profile {{ rhel8cis_authselect['custom_profile_name'] }} -b {{ rhel8cis_authselect['default_file_to_copy'] }}
        args:
            warn: no
        register: rhel8cis_5_4_1_profiles_shell_output
        when: rhel8cis_5_4_1_profiles.stdout == ''

- name: "5.4.2 | PATCH | Ensure authselect includes with-faillock"
  block:
      - name: "5.4.2 | AUDIT | Ensure authselect includes with-faillock | Gather profiles and enabled features"
        shell: "authselect current | grep with-faillock"
        failed_when: false
        changed_when: false
        check_mode: no
        register: rhel8cis_5_4_2_profiles_faillock

      - name: "5.4.2 | AUDIT | Ensure authselect includes with-faillock| Show profiles"
        debug:
            msg:
                - "Below are the current custom profiles"
                - "{{ rhel8cis_5_4_2_profiles_faillock.stdout_lines }}"

      - name: "5.4.2 | PATCH | Ensure authselect includes with-faillock | Create custom profiles"
        shell: "authselect select custom/{{ rhel8cis_authselect['custom_profile_name'] }} with-faillock --force"
        args:
            warn: no
        register: rhel8cis_5_4_2_profiles_shell_output
        when: "'- with-faillock' not in rhel8cis_5_4_2_profiles_faillock.stdout_lines"

- name: "5.5.1 | PATCH | Ensure password creation requirements are configured"
  block:
      - name: "5.5.1 | PATCH | Ensure password creation requirements are configured | Set pwquality config settings"
        lineinfile:
            path: /etc/security/pwquality.conf
            regexp: "{{ item.regexp }}"
            line: "{{ item.line }}"
        with_items:
            - { regexp: '^minlen', line: 'minlen = {{ rhel8cis_pam_password.minlen }}' }
            - { regexp: '^minclass', line: 'minclass = {{ rhel8cis_pam_password.minclass }}' }
            - { regexp: '^lcredit', line: 'lcredit = 0'}
            - { regexp: '^ucredit', line: 'ucredit = 0'}
            - { regexp: '^dcredit', line: 'dcredit = 0'}
            - { regexp: '^ocredit', line: 'ocredit = 0'}

- name: "5.5.2 | PATCH | Ensure system accounts are secured"
  lineinfile:
    path: /etc/security/faillock.conf
    state: present
    line: "{{ item }}"
  loop:
      - 'deny = 3'
      - 'unlock_time = 600'
      - silent
  register: rhel8cis_5_5_2_profiles_shell_output

- name: "5.5.3 | PATCH | Ensure password reuse is limited | pwhistory"
  lineinfile:
    path: "/etc/authselect/custom/{{ rhel8cis_authselect['custom_profile_name'] }}/{{ item }}"
    state: present
    line: "password    requisite                                    pam_pwhistory.so remember={{ rhel8cis_pam_faillock.remember }} use_authtok"
    insertafter: '^password\s*requisite\s*pam_pwquality.so'
  loop:
    - system-auth
    - password-auth
  register: rhel8cis_5_5_3_profiles_shell_output

- name: "Save the current configuration"
  shell: authselect apply-changes
  when: (rhel8cis_5_4_1_profiles_shell_output.changed == true) or
        (rhel8cis_5_4_2_profiles_shell_output.changed == true) or
        (rhel8cis_5_5_2_profiles_shell_output.changed == true) or
        (rhel8cis_5_5_3_profiles_shell_output.changed == true)
