# Standards: 1.1.31
---
# Preflight checks
- name: Preflight - Fail if host is not suitable for this benchmark
  fail:
    msg: "This benchmark is suitable for RHEL9.0++"
  when: ansible_distribution_version < "9.0"
